################################################################################
#   CONFIGURATIONS FOR GENERATING FaIR DATA
################################################################################

# TRAINING SET
train:
  # Size of dataset
  size: 5000

  # Noise level applied to forcing
  noise: 0.1

  # Random seed
  seed: 5


# VALIDATION SET
val:
  # Size of dataset
  size: 200

  # Random seed
  seed: 6


# TESTING SET
test:
  # Size of dataset
  size: 5000

  # Random seed
  seed: 7
