# GRID SEARCH
search:
  # Search grid
  grid:
    # Number of samples
    n:
      - 20
      # - 40
      # - 60
      # - 80
      # - 100
      # - 150
      # - 200
      # - 300

    # Seed used to generate the samples
    seed:
      - 2
      # - 3
      # - 5
      # - 7
      # - 11
      # - 13
      # - 17
      # - 19
      # - 23
      # - 29
      # - 31
      # - 37
      # - 41
      # - 43
      # - 47
      # - 53
      # - 59
      # - 61
      # - 67
      - 71
      # - 73
      # - 79
      # - 83
      # - 89
      # - 97
      # - 101
      # - 103
      # - 107
      # - 109
      # - 113
      # - 127
      # - 131
      # - 137
      # - 139
      # - 149
      # - 151
      # - 157
      # - 163
      # - 167
      # - 173
      # - 179
      # - 181
      # - 191
      # - 193
      # - 197
      # - 199
      # - 211
      # - 223
      # - 227
      # - 229


    # Dimension of Y
    d_Y:
      - 1
      - 2
      # - 3
      # - 4
      # - 5
      # - 7
      # - 9


    # Dimension of X1
    d_X1:
      - 1
      - 2
      # - 3
      # - 4
      # - 5
      # - 7
      # - 9


    # Dimension of X2
    d_X2:
      - 1
      - 2
      # - 3
      # - 4
      # - 5
      # - 7
      # - 9



    # Proportion of semi-supervised samples
    semi_prop:
      - 0.

    poly:
     - True