################################################################################
#   CONFIGURATIONS OF HYPERPARAMS GRID SEARCH FOR KERNEL MODEL WITH MVN DATA GENERATING PROCESS
################################################################################


# DATASET
data:
  # Number of training samples
  n: 200

  # Path to Xtrain torch tensor file to sample training set from
  Xtrain_path: data/FaIR/Xtrain.pt

  # Path to Ytrain torch tensor file to sample training set from
  Ytrain_path: data/FaIR/Ytrain.pt

  # Dimensionality of X1
  d_X1: 1

  # Dimensionality of X2
  d_X2: 1

  # Dimensionality of Y
  d_Y: 1

  # Standard deviation of noise applied to forcing
  noise: 0.1

  # Proportion of semi-supervised samples (added on top of train samples -- 1 = 100%)
  semi_prop: 200



# EVALUATION
evaluation:
  # Path to Xval torch tensor file to validate over
  Xval_path: data/FaIR/Xval.pt

  # Path to Yval torch tensor file to validate over
  Yval_path: data/FaIR/Yval.pt




# GRID SEARCH
search:
  # Number of cores for search parallelisation
  n_jobs: 4

  # Search grid for baseline model
  baseline_grid:
    # Seed for data generation
    seed:
      - 2
      - 3
      - 5
      - 7
      - 11

    # Lengthscale of primary kernel
    k1_lengthscale:
      - 0.5

    # Lengthscale of primary kernel
    k2_lengthscale:
      - 3.

    # KRR regularisation
    lbda_krr:
      - 0.0001

  # Search grid for "project before" model
  before_grid:
    # Seed for data generation
    seed:
      - 2
      - 3
      - 5
      - 7
      - 11

    # Lengthscale of primary kernel
    k1_lengthscale:
      - 0.5

    # Lengthscale of primary kernel
    k2_lengthscale:
      - 3.

    # Lengthscale of secondary kernel
    l_lengthscale:
      - 2.

    # KRR regularisation
    lbda_krr:
      - 0.0001

    # CME regularisation
    lbda_cme:
      - 0.1



  # Search grid for "project after" model
  after_grid:
    # Seed for data generation
    seed:
      - 2
      # - 3
      # - 5
      # - 7
      # - 11

    # Lengthscale of primary kernel
    k1_lengthscale:
      - 6.
      # - 8.
      # - 10.


    # Lengthscale of primary kernel
    k2_lengthscale:
      - 6.
      # - 8.
      # - 10.


    # Lengthscale of secondary kernel
    l_lengthscale:
      - 6.
      # - 8.
      # - 10.


    # KRR regularisation
    lbda_krr:
      - 0.0001
      # - 0.001
      # - 0.01

    # CME regularisation
    lbda_cme:
      - 0.01
      # - 0.1
      # - 0.5
      # - 1.
