################################################################################
#   CONFIGURATIONS FOR KERNEL MODEL WITH LINEAR DATA GENERATING PROCESS
################################################################################

# DATASET
data:
  # Number of training samples
  n: 200

  # Dimensionality of X1
  d_X1: 3

  # Dimensionality of X2
  d_X2: 3

  # Dimensionality of Y
  d_Y: 1

  # Proportion of semi-supervised samples (>0)
  semi_prop: 0.5

  # Random seed for training set generation
  seed: 5


# MODEL
model:
  # CME estimate
  cme:
    # Regularisation weight for CME estimation
    lbda: 1.

  # Baseline model
  baseline:
    # Regularisation weight for baseline model
    lbda: 1.

  # Solving for ERM inside projected RKHS = "project before"
  project_before:
    # Regularisation weight for "project before" model
    lbda: 1.

  # Solving for ERM in full RKHS and then projecting = "project after"
  project_after:
    # Regularisation weight for "project after" model
    lbda: 1.


# EVALUATION
evaluation:
  # Number of samples to use for evaluation
  n_test: 5000

  # Random seed for testing set generation
  seed: 42
