################################################################################
#   CONFIGURATIONS FOR KERNEL MODEL WITH LINEAR DATA GENERATING PROCESS
################################################################################

# DATASET
data:
  # Number of training samples
  n: 600

  # Dimensionality of X1
  d_X1: 3

  # Dimensionality of X2
  d_X2: 3

  # Dimensionality of Y
  d_Y: 1

  # Standard deviation of noise applied to X1
  noise: 0.1

  # Proportion of semi-supervised samples (>0)
  semi_prop: 3.

  # Random seed for training set generation
  seed: 5


# MODEL
model:
  # CME estimate
  cme:
    # Regularisation weight for CME estimation
    lbda: 0.1

  # Baseline model
  baseline:
    # Regularisation weight for baseline model
    lbda: 0.001

  # Primary kernel
  k:
    # RBF lengthscale
    lengthscale: 10.

  # Secondary kernel
  l:
    # RBF lengthscale
    lengthscale: 10.

# EVALUATION
evaluation:
  # Number of samples to use for evaluation
  n_test: 5000

  # Random seed for testing set generation
  seed: 42
