################################################################################
#   CONFIGURATIONS FOR LINEAR MODEL WITH LINEAR DATA GENERATING PROCESS
################################################################################

# DATASET
data:
  # Number of training samples
  n: 200

  # Dimensionality of X1
  d_X1: 3

  # Dimensionality of X2
  d_X2: 3

  # Dimensionality of Y
  d_Y: 3

  # Standard deviation of noise applied to X1
  noise: 0.1

  # Proportion of semi-supervised samples (>0)
  semi_prop: 0.5

  # Random seed for training set generation
  seed: 5

# EVALUATION
evaluation:
  # Number of samples to use for evaluation
  n_test: 5000

  # Random seed for testing set generation
  seed: 42
