################################################################################
#   CONFIGURATIONS FOR KERNEL MODEL WITH MVN DATA GENERATING PROCESS
################################################################################

# DATASET
data:
  # Number of training samples
  n: 50

  # Dimensionality of X1
  d_X1: 3

  # Dimensionality of X2
  d_X2: 3

  # Dimensionality of Y
  d_Y: 1

  # Standard deviation of noise applied to X1
  noise: 0.1

  # Number of semi-supervised samples
  semi_prop: 100

  # Random seed for training set generation
  seed: 2000


# MODEL
model:
  # CME estimate
  cme:
    # Regularisation weight for CME estimation
    lbda: 1.

  # Baseline model
  baseline:
    # Regularisation weight for baseline model
    lbda: 0.001

  # Solving for ERM inside projected RKHS = "project before"
  project_before:
    # Regularisation weight for "project before" model
    lbda: 0.001

  # Primary kernel
  r:
    # RBF lengthscale of r
    lengthscale: 8.

  # Secondary kernel
  l:
    # RBF lengthscale
    lengthscale: 2.


# EVALUATION
evaluation:
  # Number of samples to use for evaluation
  n_test: 5000

  # Random seed for testing set generation
  seed: 42

  # Number of samples to estimate the expectation in most_gain
  most_gain: True

  # Number of points to use to estimate most gain
  n_test_gain: 400

  # Number of samples for each point to estimate the expectation in most_gain
  n_gain: 200
